<a href="https://colab.research.google.com/github/HY-BME/bme_test_files/blob/%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B8%B0%EB%B0%98%ED%97%AC%EC%8A%A4%EC%BC%80%EC%96%B4%EA%B8%B0%EC%88%A0/test_0312.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
list1 = [1, 2, 3, 4, 5]
list2 = [10, 20, 30, 40, 50]

list_sum = [a+b for a,b in zip(list1, list2)]
list_prod = [a*b for a,b in zip(list1, list2)]

list_sum, list_prod

([11, 22, 33, 44, 55], [10, 40, 90, 160, 250])

In [3]:
student = {"Name": "Alice", "Age": 25, "Score": 90}

student["Name"], student.get("Age"), student.get("Score")

('Alice', 25, 90)

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [25, 30, 35],
    "Score": [90, 85, 88]
})

df.head()

  Name  Age  Score
0    A   25     90
1    B   30     85
2    C   35     88

In [16]:
student_list = {
    'student1': {'name': '철수', 'age': 20, 'score' : 90},
    'student2': {'name': '영희', 'age': 22, 'score' : 100},
    'student3': {'name': '민수', 'age': 23, 'score' : 80},
}

# 값 조회
print(student_list['student1']['name'], student_list['student1']['score'])

철수 90

In [13]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [23, 27, 31, 29],
    "Score": [75, 82, 90, 68]
})

df = df[df["Score"] >= 80]

df.head()

  Name  Age  Score
1    B   27     82
2    C   31     90

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [23, 27, 31, 29],
    "Score": [75, 82, 90, 68]
})

df = df[["Name", "Score"]]

df.head()

  Name  Score
0    A     75
1    B     82
2    C     90
3    D     68

In [23]:

import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Age": [23, 27, 31, 29],
    "Score": [75, 82, 90, 68]
})

#평균
print("평균" + df["Score"].mean())

#최대값
df["Score"].max();
print("최대값" + df)

#최솟값
df["Score"].min();
print("최솟값" + df)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U2'), dtype('int64')) -> None